services:
  postgres:
    image: postgres
    restart: always
    container_name: solarwatch_db_container
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solarwatch_backend_container
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - API_KEY=${API_KEY}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_SHOW_SQL=true
      - CODECOOL_APP_JWTSECRET=======================CodeCool=Spring===========================
      - CODECOOL_APP_JWTEXPIRATIONMS=86400000
      - GEO_API_URL=https://api.openweathermap.org/geo/1.0/direct?q=%s&appid=%s
      - SUN_API_URL=https://api.sunrise-sunset.org/json?lat=%s&lng=%s&date=%s

  frontend: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: solarwatch_frontend_container
    depends_on:
      - backend
    ports:
      - "5173:3111"

volumes:
  postgres_data: